// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjheombbengdoakzpobx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqaGVvbWJiZW5nZG9ha3pwb2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDg1MzAsImV4cCI6MjA2ODI4NDUzMH0.TAptXY5WNARJLvJCjeHl01o9_sApHeIvTXD9EjFsfNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});